# Site settings
title: Kasper Marstal
email: kaspermarstal@gmail.com
description: "Kasper Marstal's personal webiste."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BEBD39
  secondary: 1F8A70
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/kaspermarstal
  - title: facebook
    url: http://facebook.com/kaspermarstal
  - title: stack-overflow
    url: http://http://stackoverflow.com/users/346365/kasper-marstal
  - title: github
    url: http://github.com/kaspermarstal

# Build settings
markdown: kramdown
permalink: pretty